export const POLL_REPOSITORY = 'POLL_REPOSITORY';
export const POLL_CHOICE_REPOSITORY = 'POLL_CHOICE_REPOSITORY';
export const POLL_VOTE_REPOSITORY = 'POLL_VOTE_REPOSITORY';
export const FILE_UPLOAD_SERVICE = 'FILE_UPLOAD_SERVICE';
