export const ORGANIZATION_REPOSITORY = 'ORGANIZATION_REPOSITORY';
export const ORGANIZATION_VALIDATION = 'ORGANIZATION_VALIDATION';
export const ORGANIZATION_MEMBER_REPOSITORY = 'ORGANIZATION_MEMBER_REPOSITORY';
